### ISSUE TITLE
Swagger authentication

### ISSUE THREAD

**Issue by GVDmeijde** [joseftw/JOS.ApiKeyAuthentication#1]
Hi Josef,

I am trying to get my swagger to send the x-api-key in its header, but i cant get it to work.
Do you maybe know how to connect the swagger authentication to this API authentication method?

My latest tries where by using the 'securitydefinition' as shown in the snippet below.
`c.AddSecurityDefinition("API KEY", new OpenApiSecurityScheme
                    {
                        Name = "X-API-KEY",
                        Description = "ApiKey must appear in header",
                        Type = SecuritySchemeType.ApiKey,
                        In = ParameterLocation.Header
                    });`
Unfortunately, this was without success :(

I hope you can help me,
Thanks in advance,
Gijs

**Comment by joseftw** [comment]
Yes I do :)
Will see if I have time to create a quick blog post later, or just update this repo with CODE

**Comment by joseftw** [comment]
I dont have time to create a blog post right now but try this

ApiKeyConstants.HeaderName is just a string, "X-Api-Key"


    public static void Configure(IServiceCollection services)
    {
        services.AddSwaggerGen(c =>
        {
                c.AddSecurityDefinition(ApiKeyConstants.HeaderName, new OpenApiSecurityScheme
                {
                    Description = "Api key needed to access the endpoints. X-Api-Key: My_API_Key",
                    In = ParameterLocation.Header,
                    Name = ApiKeyConstants.HeaderName,
                    Type = SecuritySchemeType.ApiKey
                });

                c.AddSecurityRequirement(new OpenApiSecurityRequirement
                {
                    { new OpenApiSecurityScheme
                    {
                        Name = ApiKeyConstants.HeaderName,
                        Type = SecuritySchemeType.ApiKey,
                        In = ParameterLocation.Header,
                        Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = ApiKeyConstants.HeaderName }
                    }, new string[] {}}
                });
            });
        } `

**Comment by joseftw** [comment]
Sorry for formatting, Im on my phone

**Comment by joseftw** [comment]
Blogged about it here, hope it helps!
https://josefottosson.se/asp-net-core-tips-and-tricks-swagger-part-1/
